// <auto-generated />
namespace CrudApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddUniqueEmailConstraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUniqueEmailConstraint));
        
        string IMigrationMetadata.Id
        {
            get { return "202604220616163_AddUniqueEmailConstraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
